events {
    worker_connections 8192;
    multi_accept on;
}

http {
    # Increase upload limits
    client_max_body_size 1G;

    http3_max_concurrent_streams 1000;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    server {
        listen 443 quic reuseport;
        listen 443 ssl;

        http3 on;

        server_name http3-server;

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        ssl_protocols TLSv1.3;

        # Advertise HTTP/3
        add_header Alt-Svc 'h3=":443"; ma=86400';

        location / {
            root /var/www/html;

            # WebDAV
            dav_methods PUT DELETE MKCOL COPY MOVE;
            create_full_put_path on;
            dav_access user:rw group:rw all:r;
        }
    }
}