events {
    worker_connections 1024;
}

http {
    # Increase as needed
    client_max_body_size 1G;

    server {
        listen 443 quic reuseport;
        
        server_name http3-server;

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        ssl_protocols TLSv1.3;

        location / {
            root /var/www/html;
            add_header Alt-Svc 'h3=":443"; ma=86400';
            
            # Enable WebDAV for uploads
            dav_methods PUT DELETE MKCOL COPY MOVE;
            create_full_put_path on;
            
            # Set permissions (adjust as needed)
            dav_access user:rw group:rw all:r;
        }
    }
}