# Listen for IPv4 connections
listen=YES
listen_ipv6=NO

# Enable local user login and writing files
local_enable=YES
write_enable=YES

# Set port range for ftp passive connections
pasv_min_port=21100
pasv_max_port=21110